version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - run: bundle exec rspec
      - run: wget -c -q https://github.com/coverallsapp/coverage-reporter/releases/download/0.1.2/coveralls-linux.tar.gz -O - | tar -xz && ./coveralls -f coverage/lcov/project.lcov

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - circle
