version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:2.1.4
      - run:
          name: Install dependencies with bundler
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - circle-ci
